// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

// qmk compile -kb uterus -km default
// sudo avrdude -p m32u4 -c avr109 -P /dev/ttyACM0  -U flash:w:uterus_default.hex

// this overrides the autogenerated macro in `default_keyboard.h`
// I couldn't get it to generate the correct macro from info.json
// clang-format off
#define LAYOUT_UTERUS(k0A, k0B, k0C, k0D, k0E, k0F, k1A, k1B, k1C, k1D, k1E, k1F, k2A, k2B, k2C, k2D, k2E, k2F, k2G, k3A, k3B, k3C, k3D, k3E, k3F, k3G, k4A, k4B, k4C, k4D, k4E, k4F, k4G, k5A, k5B, k5C, k5D, k5E, k5F, k6A, k6B, k6C, k6D, k6E, k6F, k7A, k7B, k7C, k7D, k7E, k7F, k7G, k8A, k8B, k8C, k8D, k8E, k8F, k8G, k9A, k9B, k9C, k9D, k9E, k9F, k9G) { \
	 {k0A, k0B, k0C, k0D, k0E, k0F, KC_NO}, \
	 {k1A, k1B, k1C, k1D, k1E, k1F, KC_NO}, \
	 {k2A, k2B, k2C, k2D, k2E, k2F, k2G}, \
	 {k3A, k3B, k3C, k3D, k3E, k3F, k3G}, \
	 {k4A, k4B, k4C, k4D, k4E, k4F, k4G}, \
	 {k5F, k5E, k5D, k5C, k5B, k5A, KC_NO}, \
	 {k6F, k6E, k6D, k6C, k6B, k6A, KC_NO}, \
	 {k7G, k7F, k7E, k7D, k7C, k7B, k7A}, \
	 {k8G, k8F, k8E, k8D, k8C, k8B, k8A}, \
	 {k9G, k9F, k9E, k9D, k9C, k9B, k9A} \
}

#define LM_LCTL		LM(1,MOD_LCTL)
#define LM_LGUI 	LM(1,MOD_LGUI)
#define OSM_LGUI 	OSM(MOD_LGUI)
#define OSM_LCTL 	OSM(MOD_LCTL)
#define OSM_LSFT 	OSM(MOD_LSFT)

//#define HOME_N 	LSFT_T(KC_N)
#define HOME_S 	LGUI_T(KC_S)
#define HOME_T 	LCTL_T(KC_T)
#define HOME_C 	LALT_T(KC_C)

#define HOME_H  LALT_T(KC_H)
#define HOME_A	RCTL_T(KC_A)
#define HOME_E 	RGUI_T(KC_E)
//#define HOME_I 	RSFT_T(KC_I)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_UTERUS(
		KC_ESC,   	KC_F1,    KC_F2,    QK_REP,   QK_REP,   KC_F5,
        KC_TAB, 	KC_X,	  KC_F,		KC_D,	  KC_P, 	KC_Q,
        KC_BSPC,  	KC_N,	  HOME_S, 	HOME_T,	  HOME_C,	KC_Y,   	QK_REP,
        KC_UNDS,  	KC_B,     KC_V,		KC_K,	  KC_G,		KC_W,   	QK_REP,
        LM_LCTL,  	KC_ENT,   KC_LGUI,  KC_LALT,  OSM_LSFT,	KC_SPC,     QK_REP,

		            _______,  QK_REP,   QK_REP,   QK_REP,   QK_REP,     _______,
		            KC_J,	  QK_AREP,	KC_O,     KC_U,		KC_COMMA,	QK_REP,
		QK_REP,     KC_M,     HOME_H,	HOME_A,	  HOME_E,	KC_I,   	KC_UNDS,
		QK_REP,     KC_Z,     KC_L,		KC_QUOT,  KC_SLSH,	KC_DOT,   	KC_ENT,
        MO(3),  	LT(3,KC_R),MO(2),  	_______,  _______,	_______,    KC_ENT
	),
	[2] = LAYOUT_UTERUS(
		_______,   	_______,  _______,  _______,  _______,  _______,
        _______,	KC_GRV,   KC_LT,	KC_GT,	  KC_HASH,  KC_AMPR,
        _______,  	KC_EXLM,  KC_MINS, 	KC_PLUS,  KC_EQL,	KC_PIPE,   	_______,
        _______,  	KC_CIRC,  KC_UNDS,  KC_ASTR,  KC_BSLS,  KC_TILD,   	_______,
        _______,  	_______,  _______,  _______,  _______,	_______,    _______,

		            _______,  _______,  _______,  _______,  _______,    _______,
		            KC_DLR,   KC_DLR,   KC_LBRC,  KC_RBRC,  KC_PERC,	_______,
		_______,    KC_DLR,   KC_SCLN,  KC_LPRN,  KC_RPRN,  KC_QUES,   	_______,
		_______,    KC_DLR,   KC_COLN,  KC_LCBR,  KC_RCBR,	KC_AT,   	_______,
        _______,  	_______,  _______,  _______,  _______,	_______,    _______
	),
	[3] = LAYOUT_UTERUS(
		_______,   	_______,  _______,  _______,  _______,  _______,
        _______,   	_______,  KC_DEL,	KC_INS,   KC_DEL,   _______,
        _______,   	KC_7,     KC_5,  	KC_3,     KC_1,     KC_9,   	_______,
        _______,   	KC_HOME,  KC_END,   KC_PGUP,  KC_PGDN,  _______,   	_______,
        _______,  	_______,  _______,  _______,  _______,	_______,    _______,

		            _______,  _______,  _______,  _______,  _______,  	_______,
		            _______,  _______,  _______,  _______,  _______,  	_______,
		_______,   	KC_8,     KC_0,  	KC_2,     KC_4,     KC_6,       _______,
        _______,   	_______,  KC_LEFT,  KC_UP,    KC_DOWN,  KC_RIGHT, 	KC_PSCR,
        _______,  	_______,  _______,  _______,  _______,	_______,    _______
	),
	[1] = LAYOUT_UTERUS(
		KC_GRV,   _______,	_______,  _______,	_______,	_______,
        _______,  KC_Q,	    KC_W,     KC_E,	    KC_R,	    KC_T,
        _______,  KC_A,	    KC_S,     KC_D,	    KC_F,	    KC_G,       _______,
        _______,  KC_Z,	    KC_X,     KC_C,	    KC_V,	    KC_B,       _______,
        _______,  _______,	_______,  _______,	_______,	_______,    _______,

                  _______,	_______,  _______,	_______,	_______,    _______,
                  KC_Y,	    KC_U,     KC_I,	    KC_O,	    KC_P,       _______,
        _______,  KC_H,	    KC_J,     KC_K,	    KC_L,	    KC_SCLN,    _______,
        _______,  _______,	KC_LEFT,  KC_UP,    KC_DOWN,  	KC_RIGHT,   _______,
        _______,  _______,	_______,  _______,	_______,	_______,    _______
	)
};

uint16_t get_alt_repeat_key_keycode_user(uint16_t keycode, uint8_t mods) {
    switch (keycode) {
        case KC_N: return KC_X;  
        case HOME_S: return KC_F;  
        case HOME_T: return KC_D;  // For "TD" bigram.
		case HOME_C: return KC_P;

		case KC_B: return KC_X;
		case KC_V: return KC_F;
		case KC_K: return KC_D;
		case KC_G: return KC_P;
		
		case KC_X: return KC_B;
		case KC_F: return KC_V;
		case KC_D: return KC_K;
		case KC_P: return KC_G;

		case HOME_A: return KC_O; 
		case HOME_E: return KC_U; 


        case KC_O: return KC_A;
        case KC_U: return KC_E; 

    }

    return KC_TRNS;
}

	// [5] = LAYOUT_UTERUS(
	// 	_______,   	_______,  _______,  _______,  _______,  _______,
    //     _______,   	_______,  _______,  _______,  _______,  _______,
    //     _______,   	_______,  _______,  _______,  _______,  _______,   	_______,
    //     _______,   	_______,  _______,  _______,  _______,  _______,   	_______,
    //     _______,  	_______,  _______,  _______,  _______,	_______,    _______,

	// 	            _______,  _______,  _______,  _______,  _______,  	_______,
	// 	            _______,  _______,  _______,  _______,  _______,  	_______,
	// 	_______,   	_______,  _______,  _______,  _______,  _______,   	_______,
    //     _______,   	_______,  _______,  _______,  _______,  _______,   	_______,
    //     _______,  	_______,  _______,  _______,  _______,	_______,    _______
	// )

// strand
    // [2] = LAYOUT_UTERUS(
	// 	_______,   	_______,  _______,  _______,  _______,  _______,
    //     _______,	KC_V,	  KC_M,		KC_L,	  KC_F, 	KC_Q,
    //     _______,  	KC_S,	  KC_T, 	KC_R,	  KC_H,	    KC_B,   	_______,
    //     _______,  	KC_Z,     KC_J,		KC_X,	  KC_D,		KC_K,   	_______,
    //     _______,  	_______,  _______,  _______,  _______,	_______,    _______,

	// 	            _______,  KC_LEFT,  KC_UP,    KC_DOWN,  KC_RIGHT,   _______,
	// 	            KC_SLSH,  KC_Y,		KC_O,     KC_U,		KC_DOT,		_______,
	// 	_______,    KC_G,     KC_C,		KC_A,	  KC_E,		KC_I,   	_______,
	// 	_______,    KC_P,     KC_W,		KC_QUOT,  KC_SCLN,	KC_COMMA,   _______,
    //     _______,  	KC_N,	  _______,  _______,  _______,	_______,    _______
	// ),