// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H

// qmk compile -kb uterus -km default
// sudo avrdude -p m32u4 -c avr109 -P /dev/ttyACM0  -U flash:w:uterus_default.hex

// this overrides the autogenerated macro in `default_keyboard.h`
// I couldn't get it to generate the correct macro from info.json
#define LAYOUT(k0A, k0B, k0C, k0D, k0E, k0F, k1A, k1B, k1C, k1D, k1E, k1F, k2A, k2B, k2C, k2D, k2E, k2F, k2G, k3A, k3B, k3C, k3D, k3E, k3F, k3G, k4A, k4B, k4C, k4D, k4E, k4F, k4G, k5A, k5B, k5C, k5D, k5E, k5F, k6A, k6B, k6C, k6D, k6E, k6F, k7A, k7B, k7C, k7D, k7E, k7F, k7G, k8A, k8B, k8C, k8D, k8E, k8F, k8G, k9A, k9B, k9C, k9D, k9E, k9F, k9G) { \
	 {k0A, k0B, k0C, k0D, k0E, k0F, KC_NO}, \
	 {k1A, k1B, k1C, k1D, k1E, k1F, KC_NO}, \
	 {k2A, k2B, k2C, k2D, k2E, k2F, k2G}, \
	 {k3A, k3B, k3C, k3D, k3E, k3F, k3G}, \
	 {k4A, k4B, k4C, k4D, k4E, k4F, k4G}, \
	 {k5F, k5E, k5D, k5C, k5B, k5A, KC_NO}, \
	 {k6F, k6E, k6D, k6C, k6B, k6A, KC_NO}, \
	 {k7G, k7F, k7E, k7D, k7C, k7B, k7A}, \
	 {k8G, k8F, k8E, k8D, k8C, k8B, k8A}, \
	 {k9G, k9F, k9E, k9D, k9C, k9B, k9A} \
}

#define LM_LCTL LM(2,MOD_LCTL)
#define LM_LGUI LM(2,MOD_LGUI)
#define OSM_LGUI OSM(MOD_LGUI)
#define OSM_LCTL OSM(MOD_LCTL)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		KC_ESC,     KC_F1,    KC_F2,    KC_F3,    KC_F4,	KC_F5,
		KC_TAB,     KC_S,     KC_T,     KC_R,     KC_N,	    OSM_LGUI,
		KC_BSPC,    KC_I,     KC_A,	    KC_E,     KC_O,	    KC_DEL,	    XXXXXXX,
        LM_LCTL,    KC_LEFT,  KC_DOWN,	KC_UP,    KC_RIGHT,	KC_P5,	    XXXXXXX,
        LM_LCTL,    LM_LGUI,  LM_LGUI,	KC_LALT,  KC_ENT,	KC_SPC,	    OSM_LCTL,

				    KC_F6,    KC_F7,	KC_F8,    KC_F9,	KC_F10,	    KC_F11,
		            OSM_LGUI, KC_N,	    KC_R,     KC_T,	    KC_S,	    KC_F12,
		XXXXXXX,    KC_DEL,	  KC_O,     KC_E,     KC_A,     KC_I,	    KC_BSPC,
		XXXXXXX,	XXXXXXX,  KC_LEFT,  KC_UP,	  KC_DOWN,  KC_RIGHT,	KC_P6,
		OSM_LCTL,	KC_SPC,   KC_ENT,	KC_P3,    KC_P4,	KC_P5,	    KC_PSCR
	),
    [1] = LAYOUT(
		XXXXXXX,    XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,
		XXXXXXX,    KC_F4,	  KC_F3,    KC_F2,	  KC_F1,	KC_D,
		XXXXXXX,    KC_F8,    KC_F7,    KC_F6,    KC_F5,	KC_F,       XXXXXXX,
		XXXXXXX,    XXXXXXX,  XXXXXXX,	XXXXXXX,  XXXXXXX,	XXXXXXX,    XXXXXXX,
        XXXXXXX,    XXXXXXX,  XXXXXXX,	XXXXXXX,  KC_B,	    KC_A,       KC_B,

		            XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,  XXXXXXX,    XXXXXXX,
		            KC_C,	  KC_1,     KC_2,	  KC_3,	    KC_4,       XXXXXXX,
		XXXXXXX,    KC_E,     KC_5,     KC_6,     KC_7,	    KC_8,       XXXXXXX,
		XXXXXXX,    XXXXXXX,  XXXXXXX,	XXXXXXX,  XXXXXXX,	XXXXXXX,    XXXXXXX,
        KC_Y,       KC_X,     KC_Y,	    XXXXXXX,  XXXXXXX,	XXXXXXX,    XXXXXXX
	),
    [2] = LAYOUT(
		_______,  _______,	_______,  _______,	_______,	_______,
        _______,  KC_Q,	    KC_W,     KC_E,	    KC_R,	    KC_T,
        _______,  KC_A,	    KC_S,     KC_D,	    KC_F,	    KC_G,       _______,
        _______,  KC_Z,	    KC_X,     KC_C,	    KC_V,	    KC_B,       _______,
        _______,  _______,	_______,  _______,	_______,	_______,    _______,

                  _______,	_______,  _______,	_______,	_______,    _______,
                  KC_Y,	    KC_U,     KC_I,	    KC_O,	    KC_P,       _______,
        _______,  KC_H,	    KC_J,     KC_K,	    KC_L,	    KC_SCLN,    _______,
        _______,  KC_N,	    KC_M,     KC_COMMA,	KC_DOT,	    KC_SLASH,   _______,
        _______,  _______,	_______,  _______,	_______,	_______,    _______
	)
};

#include "keymap_combo.h"
